sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - IMAGE=citizengaia/tomcat-base
    - CURRENT=1.0-SNAPSHOT

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info

after_success:
  - mkdir -p '/tmp/logs/'
  - docker tag $IMAGE:$CURRENT $IMAGE
  - docker run --rm -d -p '8080:8080' -v '/tmp/logs:/hostfs/tomcat/logs' --name=tomcat $IMAGE  
  # test running container
  - curl -s -S -o responsefile http://localhost:8080/
  - grep -E "OK" responsefile || echo "wrong response from tomcat base image"
  # running container  
  - echo "OK response from tomcat base image"
  # stop container 
  - docker stop tomcat 
  - ls -lrt '/tmp/logs/'
  - tail -10 '/tmp/logs/docker-entrypoint.log'
  # Before Deploy
  - docker login --username $dockerhub_user --password $dockerhub_pass  
  # Deployment
  - docker push $IMAGE  
  # After Deploy
  - docker logout
